### ISSUE TITLE
Killed processes returns with exit code 0

### ISSUE THREAD

**Issue by hpoul** [brettwooldridge/NuProcess#10]
Hi,
When launching a process which is later killed i always see a onExit(int statusCode) call with statusCode=0 - which make it look like the process finished successfully, while in reality it was killed.

e.g. a shell script called killtest.sh with the contents:

    #!/bin/bash
    kill -6 $$

will give me the following output in bash:

    $ ./killtest.sh ; echo $?
    Abort trap: 6
    134

but when executing with NuProcess my callback receives a statusCode of 0 - how can I detect that the process was killed and not finished successfully? is this the intended behaviour? I'm not sure how a kill is actually propagated to the parent process.

the output of the following java code: https://gist.github.com/hpoul/b7ab5b58c32c7dfd463d

    Started process
    Command exited with exit code 0

i have tested this on mac and linux with nuprocess 0.9.4

thanks,
 herbert

**Comment by brettwooldridge** [comment]
@hpoul Linux side of this is fixed.

I wanted to note that the gist you provided does contain an error.  The line that reads:
```java
NuProcessBuilder processBuilder = new NuProcessBuilder("/Users/herbert/bin/killtest.sh");
```
should be
```java
NuProcessBuilder processBuilder = new NuProcessBuilder("/bin/bash", "src/test/java/com/zaxxer/nuprocess/killtest.sh");
```

**Comment by fgutmann** [comment]
Thanks for fixing this!
