### ISSUE TITLE
Can it support sending key event into the child process?

### ISSUE THREAD

**Issue by hyee** [brettwooldridge/NuProcess#15]
Say that try to invoke a child process to run Plink(pure cli of Putty) to remote to a linux server and run the "more" command,  the process is stuck on waiting for key event to scroll to next page, seems that nothing can do to let it continue. Any way to resolve this issue? Thanks.

**Comment by brettwooldridge** [comment]
@hyee My company actually uses NuProcess with plink, with no problems.  What have you tried?  Maybe you can post a [gist](https://gist.github.com) with some example code.  In a nutshell, you should be able to send any character (space, carriage-return, etc) through either the ``NuProcess.writeStdin()`` method, or by implementing a ``NuProcessHandler`` where the ``onStdout()`` method watches for the more prompt, calls ``wantWrite()`` on the NuProcess instance, and then writes a space character when the handler's ``onStdinReady()`` method is called.

**Comment by hyee** [comment]
Could you show an example of how to invoke plink via NuProcess?  I am not good at Java and ran into following problems:
    -  High cpu after successfully ssh to the remote server
    -  Cannot correctly display the ansi color characters, expected as "\e[01;31m..", but returns "@^@^@^@..."
    - The buffer parameter of onStdout is always not a null value which means EOF, instead, it outputs some strange characters periodically.

Below is the related source code:
     
    class ProcessHandler extends NuAbstractProcessHandler {
        private NuProcess nuProcess;
        private ByteBuffer keyBuffer = ByteBuffer.allocate(10);
        private LinkedList<String> cmdList = new LinkedList<String>();

        @Override
        public void onStart(NuProcess nuProcess) {
            this.nuProcess = nuProcess;
        }



        public void clear() {
            cmdList.clear();
        }

        public void close() {
            nuProcess.destroy();
        }

        //Send key event
        public void sendKey(String ch) {
            clear();
            keyBuffer.put(ch.getBytes());
            keyBuffer.flip();
            nuProcess.writeStdin(keyBuffer);
        }

        //Send command
        public void write(String stack) {
            cmdList.add(stack + "\n");
            //nuProcess.hasPendingWrites();
            nuProcess.wantWrite();
        }

        public synchronized Boolean isPending() {
            return nuProcess.hasPendingWrites();
        }

        @Override
        public boolean onStdinReady(ByteBuffer buffer) {
            if (!cmdList.isEmpty()) {
                String cmd = cmdList.poll();
                buffer.put(cmd.getBytes());
                buffer.flip();
            }
            return !cmdList.isEmpty();
        }

        @Override
        public void onStdout(ByteBuffer buffer) {
            if (buffer == null) {
                nuProcess.wantWrite();
                return;
            };
            int remaining=buffer.remaining();
            byte[] bytes = new byte[buffer.remaining()];
            buffer.get(bytes);
            writer.print(new String(bytes));
            writer.flush();
            nuProcess.wantWrite();
            // We're done, so closing STDIN will cause the "cat" process to exit
            //nuProcess.closeStdin();
        }

        @Override
        public void onStderr(ByteBuffer buffer) {
            if (buffer != null) {
                this.onStdout(buffer);
            } else nuProcess.wantWrite();
        }
    }
