### ISSUE TITLE
Pipe and redirection support

### ISSUE THREAD

**Issue by mohitbaskota** [brettwooldridge/NuProcess#16]
Hi
I am trying to execute following command from nuprocess
cat file1 file2 file3 > outputfile
The command is valid in a linux shell but can't be executed through nuprocess. Is there any idea in which such types of commands can be run through nuprocess?

**Comment by brettwooldridge** [comment]
A pipe redirection like that is part of the shell process, so you would need to do something like:
```sh
/bin/sh -c "cat file1 file2 file3 > outputfile"
```
