### ISSUE TITLE
Process termination not detected

### ISSUE THREAD

**Issue by rdicroce** [brettwooldridge/NuProcess#17]
I'm running Linux (specifically, Mint 17.1) in VirtualBox. I'm trying to use NuProcess to execute a ping, then check the exit code to determine whether a destination is reachable.

The ping process terminates and goes into a zombie state, but NuProcess never detects that this has happened. I'm not sure why, but while attempting to debug the problem, I have determined that something seems to be wrong in ProcessEpoll. I set breakpoints in the process() method and stepped through it, and noticed that ident is always 0. So linuxProcess ends up always being null and the method returns without doing anything else.

I haven't touched any settings, so they should all have the default values.

My test code is below. The handler's onStart() gets invoked, but onExit() is never called. The System.in.read() is just there to block the main thread from terminating, to make it easier to see what's happening.

```java
import java.util.ArrayList;

import com.zaxxer.nuprocess.NuAbstractProcessHandler;
import com.zaxxer.nuprocess.NuProcess;
import com.zaxxer.nuprocess.NuProcessBuilder;

public class NuProcessTest {

	public static void main(String[] args) throws Exception {
		ArrayList<String> pingCommand = new ArrayList<>(8);
		pingCommand.add("ping");
		pingCommand.add("-c");
		pingCommand.add("1");
		pingCommand.add("-W");
		pingCommand.add("2");
		pingCommand.add("www.example.com");
		
		NuAbstractProcessHandler handler = new NuAbstractProcessHandler() {
			@Override
			public void onStart(NuProcess nuProcess) {
				System.out.println("process started");
			}

			@Override
			public void onExit(int statusCode) {
				System.out.println("process terminated, code " + statusCode);
			}
		};
		
		new NuProcessBuilder(handler, pingCommand).start();
		
		System.in.read();
	}
	
}
```

**Comment by brettwooldridge** [comment]
This looks like a race condition where in which an extremely short-lived process actually runs and exits before the epoll is even setup.  I suspect if the process were longer-lived, for example if "-c" was "3" instead of "1", the race condition would not be hit.  Either way, it does appear to be a race, and we will have to investigate the best fix.

**Comment by rdicroce** [comment]
This problem does not appear to be related to the lifetime of the process. I just re-tested with -c set to 5. By default there is a 1 second gap between pings, so that makes the lifetime of the ping process at least 5 seconds, which I confirmed with ps. onExit() is still not called and the ping process is still a zombie.

**Comment by rdicroce** [comment]
I've opened a PR that fixes this issue. The main problem was that epoll_data was being treated as a struct instead of a union, so the wrong amount of memory was being allocated and the FD was being written to the wrong place.

**Comment by rdicroce** [comment]
Just updated the PR to address an embarrassing error that broke 32-bit Linux.

**Comment by brettwooldridge** [comment]
Merged.
