### ISSUE TITLE
Option to set environment explicitly on construction

### ISSUE THREAD

**Issue by cladden** [brettwooldridge/NuProcess#22]
In some cases, the caller might want to set the environment explicitly instead of using the System defaults.

Example:

```
public NuProcessBuilder(List<String> commands, Map<String, String> environment)
```

**Comment by bturner** [comment]
It seems like this issue should be closed. The suggested `NuProcessBuilder` constructor exists now.
* If you use `NuProcessBuilder(List, Map)`, the environment you pass completely replaces any existing environment
* If you use one of the other constructors, the environment is inherited from the current process

I think that's what this was asking for?
