### ISSUE TITLE
Option to set namedPipeCounter in WindowsProcess

### ISSUE THREAD

**Issue by aghahramani** [brettwooldridge/NuProcess#51]
Windows:
Bug: If we launch a subprocess using NuProcess in jvm number one and wait for subprocess to finish (waitfor(0,sec)) assuming the subprocess takes a long time to finish, then we cannot launch another subprocess using NuProcess in jvm number two because namedPieCounter (WindowsProcess.java line 95) is set to 100 by default in both jvms so when checkPipeConnected(WindowsProcess.java line 501) is called we will have name collision on pipenames and the pipe will not connect.
Fix:
Give access to namePipeCounter so we can change it in onPreStart method.

**Comment by aghahramani** [comment]
I see this has been fixed in 1.0.4

**Comment by brettwooldridge** [comment]
@aghahramani Yes, fixed thanks to @bhamiltoncx.

**Comment by bhamiltoncx** [comment]
Yes, I fixed it in 4b8c94b60059f114713029bc9bd7f4a8b0b7bcac.
