### ISSUE TITLE
Obtain PID

### ISSUE THREAD

**Issue by MTyson** [brettwooldridge/NuProcess#59]
Using a library (or similar hackery) like this [Flapdoodle](https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/runtime/Processes.java), it is possible to obtain the PID of a standard Java Process object.

Is that possible to do with a NuProcess object?

**Comment by isaiah** [comment]
This is already available via `getPid()`, the [javadoc](http://brettwooldridge.github.io/NuProcess/apidocs/index.html) inforamtion is not complete as the `BasePosixProcess` class is hidden by the `internal` namespace.

https://github.com/brettwooldridge/NuProcess/blob/master/src/main/java/com/zaxxer/nuprocess/internal/BasePosixProcess.java#L363

**Comment by brettwooldridge** [comment]
@isaiah That is correct.  If you cast the ``NuProcess`` instance to a ``BasePosixProcess`` you can access the ``getPid()`` method.  We will consider elevating this method to the ``NuProcess`` interface.

**Comment by MTyson** [comment]
Is there anyway to get the pid from the HANDLE reference?  I need this on both nix and win.

**Comment by brettwooldridge** [comment]
@MTyson Not currently, at least without writing some custom [JNA](https://github.com/java-native-access/jna).  That is why I marked this as an enhancement request.

May I ask why you need the pid?

**Comment by MTyson** [comment]
@brettwooldridge There are three reasons.  One is to help debugging, to see explicitly what processes are being created in the os.  Another is to have the ability to issue a os level kill (especially in windows, where taskkill /t seems to sometimes be necessary to ensure all subprocesses are eliminated).  A third is the most important -- our platform sometimes creates daemons that we want to later kill via platform command.  In that case, we want to save the pid off in a file, and later use it to kill the process.

I should mention that the experience of working with NuProcess has been a LOT better than the standard Process.  Everything seems to just work, and the handling of the output is much easier.  Thanks for that.

**Comment by brettwooldridge** [comment]
@MTyson Thanks for the use-cases, and for using NuProcess.  This one should be fairly easy, so I'll try to get it in this week.  I'll let you know when an artifact has been published.

**Comment by MTyson** [comment]
That is awesome.  Looking forward to using it.

**Comment by MTyson** [comment]
@brettwooldridge I've been looking at it a bit.  

The nix side should be easy, as you guys mentioned.

For windows, I haven't worked with JNA before, but it looks like what we need is not in `kernel32`.  I hate to go off into the weeds, can you tell me what you are thinking for a solution?  

I can put something together and submit a pull, if that will be helpful.  lmk.

**Comment by MTyson** [comment]
It turned out to be pretty easy.  There was a method on kernel32.  I added a pull request.
