### ISSUE TITLE
WindowsProcess printStackTrace

### ISSUE THREAD

**Issue by benor1470** [brettwooldridge/NuProcess#63]
Hey, the WindowsProcess  uses printStackTrace (lines 173,220,249,303,332,392) and not using logger, can you please use a logger so i can turn in off when they aren't needed?
My log shows those errors on tests and without a way to turn them off they fill my log

Thank you

**Comment by brettwooldridge** [comment]
Pull requests welcomed.

**Comment by fanf** [comment]
I have the same problem with ```BasePosixProcess```. 
I have two concerns: 
- I can't adapt (and potentially recover at the application logic level) from the error that appears in the stacktrace, and which is not always an exception from the application logic
- I have non-contextualise stacktrace. Typically, when I get "Invocation of posix_spawn() failed, return code: 13, last error: 13", I would prefer to tell my user to look at the command permission (with the path to the command), but never ever display that message to them. 

To not depend to a given log framework, and idea could be to add a ```PrinStream``` to the process builder, and use that one in place of ```System.err``` if provided. 
Users who care would be able to provide a byte array output stream to post process the stream in case of exit code ```Int.MinValue```, and chose what to actually disaply to users using their application logging framework. 

Do you think the idea can fly ?

**Comment by bturner** [comment]
In the years since this was last updated, `BasePosixProcess` has already been changed to replace `e.printStackTrace` with use of the JDK's `java.util.logging.Logger`, and 1.2.x and 2.0.x releases include that change. I've recently opened pull request #118 which applies a similar treatment to `WindowsProcess`. Hopefully that can be merged/released soon.

**Comment by bturner** [comment]
My changes from pull request #118 were included in NuProcess 2.0.2, eliminating the last `e.printStackTrace` calls from the codebase.
