### ISSUE TITLE
Expose exitCode on NuProcess

### ISSUE THREAD

**Issue by cdancy** [brettwooldridge/NuProcess#69]
Can we expose exitCode on the NuProcess interface? If there is no reason why we can't I can submit a PR for this change.

**Comment by cdancy** [comment]
@brettwooldridge any thoughts?

**Comment by brettwooldridge** [comment]
@cdancy Any reason you can't use the ``NuProcessHandler.onExit(int exitCode)`` callback, or the value returned by ``NuProcess.waitFor()``?

**Comment by cdancy** [comment]
@brettwooldridge that works as well ;) I was looking at your README.md and assumed you had all the callback methods exposed there.
