### ISSUE TITLE
Starting daemonized processes

### ISSUE THREAD

**Issue by bramklg** [brettwooldridge/NuProcess#7]
We are trying to switch from using the regular Runtime.exec() from java to the NuProcess lib. We are using this solely on Linux. We don't realy use async processes, e.g. when we execute a process we always need to wait untill its "done". Most of the time this is to read and parse output, this works great.

However, we also have a couple of daemon processes we start (more specific: kvm/qemu). The regular behavior in Java was to return when the process was executed correctly without writing anything to stdout/stdin or return when the process could not be started (it would write output to stderror then).

After our switch to NuProcess we can't "execute and return when started correctly" anymore. We use waitFor(0, ...) directly after executing to wait untill the process is don e but this call hangs untill we kill the executed process. I understand why this is (the process is still running) but im wondering if there is a solution so we get the same behavior as with Runtime.exec?

**Comment by bturner** [comment]
It's been 8 years since this issue was last updated, and the way NuProcess forks processes has changed significantly in that time. If someone has further information about this, feel free to open a new issue for investigation.
