### ISSUE TITLE
Is there any way to set max memory used by the native library

### ISSUE THREAD

**Issue by udayshnk** [brettwooldridge/NuProcess#83]
Hi I would like to know is there any way to set the max native memory used by the library as the memory this library uses is not managed by GC. 

We have our jvm process running in a small docker container which have a max memory limit of 4 GB. That should include both heap and non heap usage. If the overall container memory reaches near 4GB we have a kernel killing the processes.

**Comment by brettwooldridge** [comment]
There is no max memory setting, but it is hard to imagine NuProcess taking more than a few megabytes total.

**Comment by udayshnk** [comment]
@brettwooldridge it didn't take up the memory. I just wanted to know if there is any setting, before we go on and use it in a production environment.
