### ISSUE TITLE
IO Network programming

### ISSUE THREAD

**Issue by devzonetrack** [brettwooldridge/NuProcess#96]
Iam new about NuProcess, is possible to create TCP Server nonblocking  with NuProcess? any sample?

**Comment by lfbayer** [comment]
NuProcess is designed for executing and interacting with child processes. It won't help you with running a network server.

You might take a look at [netty](https://mina.apache.org/) or [Apache MINA](https://mina.apache.org/)

**Comment by vietj** [comment]
or Vert.x https://vertx.io/docs/vertx-core/java/#_writing_tcp_servers_and_clients :-)

**Comment by vietj** [comment]
Vert.x has an out of the box integration with Nuprocess as https://github.com/vietj/childprocess-vertx-ext
